### ISSUE TITLE
주제 초안

### ISSUE THREAD

**Issue by 2jeongin** [YangDaeGwan/LeeKimYang#1]
[오픈소스기초프로젝트]

팀 프로젝트를 위한 주제 초안을 작성해 주세요.
주제는 한 개 이상 작성 부탁드립니다.

(양식)

<주제 이름(가명 상관 없음.)>
- 주제에 대한 대한 설명 (내용, 필요한 이유, 사용자 예상 등)

**Comment by 2jeongin** [comment]
<마트 비교 서비스>
- 자신이 검색한 마트(편의점, 슈퍼 등 포함)의 물품 가격을 확인할 수 있는 서비스이다. 특정 품목에 관해 가격이 더 싼 마트를 찾아 물건을 구매할 수 있다.
- 서비스를 확장하여 게시판(과일이 맛있다, 생선이 신선하다 등), 해당 점포의 주차장 등 정보를 추가로 제공할 수 있다.

<영양제 추천 서비스>
- 카테고리(연령, 필요 영양 등)를 구분하여 자신에게 맞는 영양제를 추천해주는 서비스이다.
- 점차 높아지는 영양제 관심에 대응하여 적절한 정보를 제공할 수 있다.
- 칼슘 등 성장 관련 영양이 필요한 어린이, 건강 회복 관련 영양이 필요한 어른 등 다양한 사용자가 있을 것으로 예측한다.

**Comment by YangDaeGwan** [comment]
에타운 

- 에타운은 에브리 타운으로 우리동네에 모든 정보를 묻고 답하는 서비스입니다. 가령 공원에 얼마나 많은 사람들이 운동을 하고 있는지 궁금할 때 에타운을 통해 물어보면 공원에서 운동하고 있는 에타운 회원이 답해줄 수 있습니다. 
- 동네 인증을 통해 동네 주민들이 이용할 것입니다.

**Comment by moon9087** [comment]
<여행지 추천 서비스>

- 지역에 따라 여행지를 추천해주는 어플은 많지만 취향이나 상황에 따라 여행지를 추천해주는 어플은 없다.
- 자신의 취향이나 상황에 맞는 해시태그를 검색하면 그에 맞는 여행지를 추천해준다.
- 여행을 즐기는 사람뿐 아니라 처음 여행을 가는 사람에겓 도움이 될 수 있을 것이다.

<식단 추천 서비스>

- 많은 사람들이 매일 무엇을 먹을지 고민한다.
- 영양소, 칼로리 취향 등을 고려해 아침, 점심, 저녁의 식단을 제공한다.
- 한끼에 먹고 싶은 칼로리, 보충하고 싶은 영양소 등을 선택할 수 있다.
- 다이어트 중인 사람, 자취생 등 많은 사람들이 사용할 것이다.

**Comment by moon9087** [comment]
> <여행지 추천 서비스>
> 
> * 지역에 따라 여행지를 추천해주는 어플은 많지만 취향이나 상황에 따라 여행지를 추천해주는 어플은 없다.
> * 자신의 취향이나 상황에 맞는 해시태그를 검색하면 그에 맞는 여행지를 추천해준다.
> * 여행을 즐기는 사람뿐 아니라 처음 여행을 가는 사람에겓 도움이 될 수 있을 것이다.
> 
> <식단 추천 서비스>
> 
> * 많은 사람들이 매일 무엇을 먹을지 고민한다.
> * 영양소, 칼로리 취향 등을 고려해 아침, 점심, 저녁의 식단을 제공한다.
> * 한끼에 먹고 싶은 칼로리, 보충하고 싶은 영양소 등을 선택할 수 있다.
> * 다이어트 중인 사람, 자취생 등 많은 사람들이 사용할 것이다.

#2 

<여행지 추천 서비스> 변동사항

- 해시태그를 입력하면 그에 맞는 여행지를 추천하는 것이 아니라 산, 바다, 계곡 등의 카테고리를 선택하면 그에 맞는 여행 장소를 추천해준다.

**Comment by 2jeongin** [comment]
> <마트 비교 서비스>> 
> * 자신이 검색한 마트(편의점, 슈퍼 등 포함)의 물품 가격을 확인할 수 있는 서비스이다. 특정 품목에 관해 가격이 더 싼 마트를 찾아 물건을 구매할 수 있다.
> * 서비스를 확장하여 게시판(과일이 맛있다, 생선이 신선하다 등), 해당 점포의 주차장 등 정보를 추가로 제공할 수 있다.
> 
> <영양제 추천 서비스>
> 
> * 카테고리(연령, 필요 영양 등)를 구분하여 자신에게 맞는 영양제를 추천해주는 서비스이다.
> * 점차 높아지는 영양제 관심에 대응하여 적절한 정보를 제공할 수 있다.
> * 칼슘 등 성장 관련 영양이 필요한 어린이, 건강 회복 관련 영양이 필요한 어른 등 다양한 사용자가 있을 것으로 예측한다.



> <여행지 추천 서비스>
> 
> * 지역에 따라 여행지를 추천해주는 어플은 많지만 취향이나 상황에 따라 여행지를 추천해주는 어플은 없다.
> * 자신의 취향이나 상황에 맞는 해시태그를 검색하면 그에 맞는 여행지를 추천해준다.
> * 여행을 즐기는 사람뿐 아니라 처음 여행을 가는 사람에겓 도움이 될 수 있을 것이다.
> 
> <식단 추천 서비스>
> 
> * 많은 사람들이 매일 무엇을 먹을지 고민한다.
> * 영양소, 칼로리 취향 등을 고려해 아침, 점심, 저녁의 식단을 제공한다.
> * 한끼에 먹고 싶은 칼로리, 보충하고 싶은 영양소 등을 선택할 수 있다.
> * 다이어트 중인 사람, 자취생 등 많은 사람들이 사용할 것이다.

#2
