### ISSUE TITLE
프로젝트 계획 수정 의견

### ISSUE THREAD

**Issue by moon9087** [YangDaeGwan/LeeKimYang#10]
python을 쓰고 분류를 확실히 나타내려면 해시태그를 하는게 좋을 것 같아서요..!
트리플이나 여행 관련 사이트에서 정보를 추출한 후 해시태그를 모아놓고 선택하면 맞는 여행지를 추천해주는 선택지 하나 저희가 처음 말했던 산, 바다 등으로 나누어 선택하는 선택지 하나 이렇게 하면 어떨까요??

그러니까 맨 위에 메뉴를 만든 후에 추천, 직접선택을 고를 수 있게 하는 거죠.

도움이 될 만한 사이트 올려놓을게요!

**Comment by YangDaeGwan** [comment]
아 좋습니다!! 제가 이걸 확인하지 않고 이슈글을 올렸네요...
