### ISSUE TITLE
여행 정보 추출에 도움 될만한 사이트

### ISSUE THREAD

**Issue by moon9087** [YangDaeGwan/LeeKimYang#11]
한국 관광공사 대한민국 구석구석 https://korean.visitkorea.or.kr/main/main.do#home(한국 여행지만 있는 사이트라 비교적 많은 정보가 있는듯하고 해시태그가 있어 정보추출하기 편할 듯합니다)
트립어드바이저 https://www.tripadvisor.co.kr/(비교적 한국 여행지가 적지만 사람들의 리뷰를 볼 수 있다는 장점이 있습니다)
트리플 어플

**Comment by YangDaeGwan** [comment]
감사합니다!!
