### ISSUE TITLE
#해쉬태그, 여행 카테고리 필터

### ISSUE THREAD

**Issue by YangDaeGwan** [YangDaeGwan/LeeKimYang#12]
카테고리를 만들어서 여행지를 적절히 분류하려고 합니다. 각자 데이터 추출하신 것을 기준으로 필요한 카테고리를 적어주시면 감사하겠습니다. 그리고 나서 모여진 의견을 중심으로 의논하여 카테고리를 확정하도록 하겠습니다!! 

ex) #산 높이로 구분(100~200, 200~300, etc.)

**Comment by 2jeongin** [comment]
지역(충청북도-청주시) 선택 시

#상당구 #서원구 #청원구 #흥덕구
#혼자 #연인 #친구 #어린이 동반
#가족 #단체 #100m 이하 #100m 이상
#200m 이하 #200m 이상 #300m 이하 #300m 이상
#400m 이하 #400m 이상 #500m 이하 #500m 이상
