### ISSUE TITLE
"여행지 환경 카테고리" 디자인 소스

### ISSUE THREAD

**Issue by 2jeongin** [YangDaeGwan/LeeKimYang#14]
copyright free image 자료입니다.
![산](https://user-images.githubusercontent.com/101683551/168279847-a242b4e4-82eb-474f-baf8-16c7b5ac4de8.PNG)
![계곡2](https://user-images.githubusercontent.com/101683551/168279853-afe18fae-fe63-4817-a4ea-894fce3683be.PNG)
![바다2](https://user-images.githubusercontent.com/101683551/168279878-3373c976-1d89-45eb-ba3d-e2f5035ef7e2.PNG)
![캠핑2](https://user-images.githubusercontent.com/101683551/168279884-67c8d427-f3b3-4e14-8364-4bdeee2398d3.PNG)
![벚꽃2](https://user-images.githubusercontent.com/101683551/168279912-941ff1c6-96c8-4d43-8602-25b0335a5cb1.PNG)
![한옥2](https://user-images.githubusercontent.com/101683551/168279919-a418bc93-0acf-4968-b591-2a8d25148901.PNG)
![궁궐2](https://user-images.githubusercontent.com/101683551/168279921-59aa1876-95d1-4dd9-95b2-91571100837e.PNG)
![체험2](https://user-images.githubusercontent.com/101683551/168279917-9f12e995-9416-4d67-b1d3-fecd58b69182.PNG)

**Comment by YangDaeGwan** [comment]
감사합니다!!
