### ISSUE TITLE
주제 선정

### ISSUE THREAD

**Issue by moon9087** [YangDaeGwan/LeeKimYang#2]
첫 번째 회의(3/17)를 통해 <여행지 추천 서비스>와 <에타운>으로 주제가 좁혀졌습니다.

각자 더 추진하기 원하는 주제를 말해 주시고, 왜 그렇게 생각하는지에 대한 의견도 작성해 주세요.
주제에 관한 변동사항도 있으면 작성 부탁드립니다.

**Comment by 2jeongin** [comment]
<여행지 추천 서비스>로 진행하였으면 좋겠습니다.
<여행지 추천 서비스>가 <에타운>보다 프로젝트 테마에 해당하는 검출, 분류에 더 적합하다고 생각하기 때문입니다.

**Comment by moon9087** [comment]
여행지 추천 서비스가 더 낫다고 생각합니다.
취향 기반 여행지 추천 서비스가 없으므로 차별성이 있으면서 여행을 가려는 많은 사람에게 도움을 줄 수 있는 서비스이기 때문입니다.
