### ISSUE TITLE
산 이미지 디자인

### ISSUE THREAD

**Issue by moon9087** [YangDaeGwan/LeeKimYang#22]
![상당산](https://user-images.githubusercontent.com/101267224/171629147-113f9ae4-6667-4a7d-b1f5-a34c9df522d0.jpg)

이미지 이렇게 디자인 해봤는데 어떤가요??

**Comment by moon9087** [comment]
전체 파일입니다
[산이미지.zip](https://github.com/YangDaeGwan/LeeKimYang/files/8824226/default.zip)

**Comment by 2jeongin** [comment]
엄청 좋습니다!!
