### ISSUE TITLE
파일(이미지) 액세스 오류

### ISSUE THREAD

**Issue by 2jeongin** [YangDaeGwan/LeeKimYang#25]
git pull하여 개인 컴퓨터 내 해당 이미지가 존재하여도 홈페이지를 열면 이미지 액세스가 되지 않음

-> 파일 경로 수정
1. 이미지가 들어있는 폴더(폴더A)가 홈페이지 링크가 든 폴더(폴더B)와 같은 상위 폴더 내 각각 존재하였음.
2. 해결 방법 : '폴더A' into '폴더B'(홈페이지 링크와 폴더A가 같은 상위 폴더 내 존재해야 함.)

-> 해결 완료 #파일(이미지)이 정상적으로 액세스 됨

**Comment by YangDaeGwan** [comment]
넵 확인했습니다!!

**Comment by 2jeongin** [comment]
모두 확인하셨으니 closed 합니다!
