### ISSUE TITLE
카테고리 수정이 필요!!

### ISSUE THREAD

**Issue by YangDaeGwan** [YangDaeGwan/LeeKimYang#26]
저희가 카테고리가 여러개가 있는데 어떻게 구현하면 좋을까요? 일단 구현 문제상으로 100m 이하부터 500m이상까지를 
100m 이하, 100m 이상 200m 이하, 200m이상 300m 이하, 300m 이상 400m 이하, 400m 이상 500m 이하, 500m 이상으로 바꾸었습니다. 
그리고 카테고리 중에서 혼자, 연인, 가족 등은 나누는 기준이 애매해서 다른 것으로 수정 했으면 좋겠습니다. 카테고리를 어떻게 수정하면 좋을지 각자 의견 적어주세요!!

**Comment by moon9087** [comment]
100m 이하는 없으니까 빼고 난이도랑 몇가지 항목들 더 추가하면 좋겠습니다!

**Comment by YangDaeGwan** [comment]
넵

**Comment by 2jeongin** [comment]
YangDaeGwan, moon9087 의견에 덧붙 지역(구), 높이 카테고리 그대로 두고 어린이 동반, 등산로 유(有) 추가했으면 좋겠습니다!
