### ISSUE TITLE
세부설정 (언어 선정 및 역할 분담)

### ISSUE THREAD

**Issue by YangDaeGwan** [YangDaeGwan/LeeKimYang#3]
소프트웨어 개발 언어 선정
앱을 만들기 전에 각자가 다룰 줄 알거나 자신 있는 언어들을 적어주세요!!
ex) Python, c++, java script, etc.
여러분들의 답변을 기반으로 선정하도록하겠습니다!

역할 분담
백앤드 
프론트앤드
다같이

**Comment by moon9087** [comment]
python,c

아직 부족한 부분이 많으므로 다같이 프로젝트를 해 나가면 좋겠습니다.

**Comment by 2jeongin** [comment]
다른 언어는 아직 미숙하여 python으로 진행하고 싶습니다.

역할 분담은 프론트앤드 또는 다같이 원합니다!

**Comment by YangDaeGwan** [comment]
소프트웨어 개발 언어 : Python
다같이 서로 도와가며 열심히 해봐요!!
