### ISSUE TITLE
모델 선정

### ISSUE THREAD

**Issue by moon9087** [YangDaeGwan/LeeKimYang#5]
주제를 구체화해보려 합니다!

-주제에 적합한 모델
-모델에 필요한 데이터

자신이 생각하는 것을 올려주세요

**Comment by moon9087** [comment]
핵심 키워드 추출 모델,  분류 모델

필요한 데이터: 산, 바다, 계곡, 벛꽃, 양성산 정보, 북한산 정보, 산에 대한 리뷰, 취향에 대한 해시태그 등

**Comment by YangDaeGwan** [comment]
제가 생각하기에는 전국을 중심으로 하는 것보다 전국을 대상으로 하되 구현하는 것은 청주만 구현하면 좋을 것 같습니다. 청주를 중심으로 산 데이터를 모아보겠습니다!! 괜찮으신가요??

**Comment by moon9087** [comment]
> 제가 생각하기에는 전국을 중심으로 하는 것보다 전국을 대상으로 하되 구현하는 것은 청주만 구현하면 좋을 것 같습니다. 청주를 중심으로 산 데이터를 모아보겠습니다!! 괜찮으신가요??

좋은 것 같습니다..!
