### ISSUE TITLE
웹 제작 방법 재논의

### ISSUE THREAD

**Issue by moon9087** [YangDaeGwan/LeeKimYang#6]
제가 알아보니 아예 기초부터 만드는 것은 저희한테 좀 어려울 것 같아서 python이나 html 템플릿을 사용하는 것은 어떨까요..? 하나를 선정해서 수정할 것은 수정하고 인용할 것은 인용해 저희 프로젝트 진행하는 것도 괜찮을 것 같습니다. 
다른 분들 의견 어떠신지 말씀해주세요!

**Comment by YangDaeGwan** [comment]
넵 html이랑 css를 사용해서 웹 페이지를 만들면 좋을 것 같습니다.
