### ISSUE TITLE
웹 첫페이지 디자인(moon9087)

### ISSUE THREAD

**Issue by moon9087** [YangDaeGwan/LeeKimYang#7]
file:///C:/Users/%EA%B9%80%EC%A7%80%EC%98%81/practice1/about.html
일단 html로 이정도 만들어보았습니다. pull request도 수업시간에 배웠던 대로 해보니 꽤 되더라구요. 중간중간에 conflict가 생겨서 애를 먹긴 했지만 그 원인을 알고 극복만 하면 괜찮을 것 같습니다.

**Comment by YangDaeGwan** [comment]
주신 링크에 들어가도 아무것도 보이지 않네요..

**Comment by moon9087** [comment]
> 주신 링크에 들어가도 아무것도 보이지 않네요..
> 
> 

앗.. 다시 확인해보겠습니다

**Comment by moon9087** [comment]
https://github.com/moon9087/practice1
제가 시험삼아 해본 repository인데 이걸로 git clone하면 보일까요..?

**Comment by YangDaeGwan** [comment]
확인했습니다!! 굿이요
