### ISSUE TITLE
산 데이터 모으기

### ISSUE THREAD

**Issue by YangDaeGwan** [YangDaeGwan/LeeKimYang#8]
청주를 대상으로 산에 대한 데이터를 모으려고 합니다. 청주는 상당구, 서원구, 흥덕구, 청원구 이렇게 4개의 구로 이루어져있습니다.  제가 서원구와 흥덕구 산 데이터를 찾도록하겠습니다.  정인이 누나가 청원구 지영이가 상당구 주변의 산을 찾아서 조사해주면 좋을것 같습니다!! 
ex) 산 이름(), 주소(), 높이(), 적당한 설명을 순서대로  excel파일로 문서화해서 정리하면 될것같습니다.

**Comment by YangDaeGwan** [comment]
부가 설명 부분에는 산에대한 정보가 있는 블로그 링크를 복사하는 것도 나쁘지 않다고 생각하는데 어떻게 생각하시나요?

**Comment by YangDaeGwan** [comment]
[청주 흥덕구, 서원구 산.xlsx](https://github.com/YangDaeGwan/LeeKimYang/files/8651453/default.xlsx)

**Comment by moon9087** [comment]
> 부가 설명 부분에는 산에대한 정보가 있는 블로그 링크를 복사하는 것도 나쁘지 않다고 생각하는데 어떻게 생각하시나요?

네! 그것도 넣고 사진 몇개랑 기본적인 설명도 넣으면 좋을 것 같습니다

**Comment by moon9087** [comment]
[상당구 산 모음.xlsx](https://github.com/YangDaeGwan/LeeKimYang/files/8678938/default.xlsx)
해시태그도 달아보았습니다

**Comment by 2jeongin** [comment]
[청주 산 리스트(구별).xlsx](https://github.com/YangDaeGwan/LeeKimYang/files/8799270/default.xlsx)

올려주신 파일, 국토지리정보원, 지도 참고하여 구별로 청주지역 내 산 정리했습니다. 인터넷으로 높이 정보 찾지 못한 산은 부득이하게 ?로 표기하였습니다.
